/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekakhirperpustakaan;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DataPeminjam extends javax.swing.JFrame {
    private String statusEdit = "";
    private Koneksi koneksi;
    private Statement st;
    private String sql;
    private ResultSet rs;
    String  nama, id, status;
    public DataPeminjam() {
        initComponents();
        koneksi = new Koneksi();
        tampil_peminjam();
    }
    private void tampil_peminjam() {
    DefaultTableModel grid = new DefaultTableModel();
        grid.addColumn("ID Anggota");
        grid.addColumn("Nama");
        grid.addColumn("Status");
        try {
            ResultSet rs = koneksi.getStatement().executeQuery("SELECT * FROM anggota");
            while (rs.next()) {
                grid.addRow(new Object[]{
                        rs.getString(1), rs.getString(2), rs.getString(3)});
            }

            jTable1user.setModel(grid);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
        }
    }
    private void cariPeminjam(String id) {
        DefaultTableModel grid = new DefaultTableModel();
        grid.addColumn("ID Anggota");
        grid.addColumn("Nama");
        grid.addColumn("Status");
        try {
            String query = "SELECT * FROM anggota WHERE Nama LIKE ?";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(query);
            preparedStatement.setString(1, "%" + id + "%");
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                grid.addRow(new Object[]{
                    rs.getString(1), rs.getString(2), rs.getString(3)});
            }jTable1user.setModel(grid);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
        }
    }
    private void kosong() {
        idAnggota_txt.setText("");
        nama_txt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idAnggota_txt = new javax.swing.JTextField();
        tambah_btn = new javax.swing.JButton();
        nama_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1user = new javax.swing.JTable();
        cari_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hapus_btn = new javax.swing.JButton();
        perbaruidata_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        aktif_chk = new javax.swing.JCheckBox();
        black_chk = new javax.swing.JCheckBox();
        cari_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan Data yang Sesuai !");

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Anggota");

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status ");

        idAnggota_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        idAnggota_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAnggota_txtActionPerformed(evt);
            }
        });
        idAnggota_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idAnggota_txtKeyPressed(evt);
            }
        });

        tambah_btn.setBackground(new java.awt.Color(106, 255, 127));
        tambah_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        tambah_btn.setForeground(new java.awt.Color(0, 0, 126));
        tambah_btn.setText("SIMPAN");
        tambah_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_btnActionPerformed(evt);
            }
        });

        nama_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Anggota");

        jTable1user.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTable1user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID Anggota", "Nama", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1user);

        cari_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        cari_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_txtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Masukkan Nama Anggota*");

        hapus_btn.setBackground(new java.awt.Color(106, 255, 127));
        hapus_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        hapus_btn.setForeground(new java.awt.Color(0, 0, 126));
        hapus_btn.setText("HAPUS");
        hapus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_btnActionPerformed(evt);
            }
        });

        perbaruidata_btn.setBackground(new java.awt.Color(106, 255, 127));
        perbaruidata_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        perbaruidata_btn.setForeground(new java.awt.Color(0, 0, 126));
        perbaruidata_btn.setText("PERBARUI DATA");
        perbaruidata_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaruidata_btnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(106, 255, 127));

        jLabel6.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 126));
        jLabel6.setText("DATA ANGGOTA");

        back_btn.setBackground(new java.awt.Color(106, 255, 127));
        back_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\arrow (1).png")); // NOI18N
        back_btn.setBorderPainted(false);
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(back_btn)
                .addGap(318, 318, 318)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        aktif_chk.setBackground(new java.awt.Color(0, 0, 126));
        aktif_chk.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        aktif_chk.setForeground(new java.awt.Color(255, 255, 255));
        aktif_chk.setText("Aktif");
        aktif_chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktif_chkActionPerformed(evt);
            }
        });

        black_chk.setBackground(new java.awt.Color(0, 0, 126));
        black_chk.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        black_chk.setForeground(new java.awt.Color(255, 255, 255));
        black_chk.setText("BlackList");
        black_chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                black_chkActionPerformed(evt);
            }
        });

        cari_btn.setBackground(new java.awt.Color(106, 255, 127));
        cari_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        cari_btn.setForeground(new java.awt.Color(255, 255, 255));
        cari_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\search.png")); // NOI18N
        cari_btn.setIconTextGap(8);
        cari_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_btnActionPerformed(evt);
            }
        });

        edit_btn.setBackground(new java.awt.Color(106, 255, 127));
        edit_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(0, 0, 126));
        edit_btn.setText("EDIT");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nama_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idAnggota_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cari_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                    .addComponent(cari_btn))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(aktif_chk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(black_chk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(108, 108, 108)
                                    .addComponent(tambah_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(77, 77, 77)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(perbaruidata_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(hapus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cari_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idAnggota_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(perbaruidata_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nama_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(aktif_chk)
                                .addComponent(black_chk)))
                        .addGap(48, 48, 48)
                        .addComponent(tambah_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ARTPRINT\\panel buku.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void perbaruidata_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbaruidata_btnActionPerformed
        String id = idAnggota_txt.getText();
        String nama = nama_txt.getText();
        String status = aktif_chk.isSelected() ? "Aktif" : (black_chk.isSelected() ? "Hitam" : "");

        try {
            String sql = "UPDATE anggota SET Nama=?, Status=? WHERE id_anggota=?";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(sql);
            preparedStatement.setString(1, nama);
            preparedStatement.setString(2, status);
            preparedStatement.setString(3, id);
            preparedStatement.executeUpdate();
            tampil_peminjam();
            JOptionPane.showMessageDialog(null, "Data Behasil Diperbarui");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Inputan Salah\n" + e.getMessage());
        }
        kosong();
    }//GEN-LAST:event_perbaruidata_btnActionPerformed

    private void hapus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_btnActionPerformed
        int selectedRow = jTable1user.getSelectedRow();
         if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang Ingin Dihapus");
            return;
         }
         String id = jTable1user.getValueAt(selectedRow, 0).toString(); 

         try {
            String sql = "DELETE FROM anggota WHERE id_anggota = ?";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(sql);
            preparedStatement.setString(1, id);
            preparedStatement.executeUpdate();
            tampil_peminjam();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
         } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menghapus Data: " + e.getMessage());
         }
    }//GEN-LAST:event_hapus_btnActionPerformed

    private void cari_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_txtActionPerformed
        String namaCari = cari_txt.getText();
        cariPeminjam(namaCari);
    }//GEN-LAST:event_cari_txtActionPerformed

    private void tambah_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_btnActionPerformed
        String id = idAnggota_txt.getText();
        String nama = nama_txt.getText();
        String status = aktif_chk.isSelected() ? "Aktif" : (black_chk.isSelected() ? "Hitam" : "");
        try {
            String sql = "INSERT INTO anggota (id_anggota, Nama, Status) VALUES (?, ?, ?)";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(sql);
            preparedStatement.setString(1, id);
            preparedStatement.setString(2, nama);
            preparedStatement.setString(3, status);
            preparedStatement.executeUpdate();
            tampil_peminjam();
            JOptionPane.showMessageDialog(null, "Data Behasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Inputan Salah\n" + e.getMessage());
        }

        kosong();
    }//GEN-LAST:event_tambah_btnActionPerformed

    private void idAnggota_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAnggota_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAnggota_txtActionPerformed

    private void aktif_chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktif_chkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aktif_chkActionPerformed

    private void black_chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_black_chkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_black_chkActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        dispose();
        Home hm = new Home();
        hm.setVisible(true);
        hm.setButtonIcons();
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(Login.EXIT_ON_CLOSE); 
    }//GEN-LAST:event_back_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        int selectedRow = jTable1user.getSelectedRow();
        if (selectedRow == -1) {
           JOptionPane.showMessageDialog(null, "Pilih Baris yang Ingin Diedit");
           return;
        }
        String id = jTable1user.getValueAt(selectedRow, 0).toString();
        String nama = jTable1user.getValueAt(selectedRow, 1).toString();
        String status = jTable1user.getValueAt(selectedRow, 2).toString();
        idAnggota_txt.setText(id);
        nama_txt.setText(nama);
    }//GEN-LAST:event_edit_btnActionPerformed

    private void idAnggota_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idAnggota_txtKeyPressed
        
    }//GEN-LAST:event_idAnggota_txtKeyPressed

    private void cari_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_btnActionPerformed
        String namaCari = cari_txt.getText();
        cariPeminjam(namaCari);
    }//GEN-LAST:event_cari_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPeminjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktif_chk;
    private javax.swing.JButton back_btn;
    private javax.swing.JCheckBox black_chk;
    private javax.swing.JButton cari_btn;
    private javax.swing.JTextField cari_txt;
    private javax.swing.JButton edit_btn;
    private javax.swing.JButton hapus_btn;
    private javax.swing.JTextField idAnggota_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1user;
    private javax.swing.JTextField nama_txt;
    private javax.swing.JButton perbaruidata_btn;
    private javax.swing.JButton tambah_btn;
    // End of variables declaration//GEN-END:variables
}
