/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekakhirperpustakaan;

import java.util.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DataPeminjaman extends javax.swing.JFrame {
    private Koneksi koneksi;
    public DataPeminjaman() {
        initComponents();
        koneksi = new Koneksi();
        tampil_peminjaman();
        waktu();
        isiCmb();
    }
    private void tampil_peminjaman() {
        DefaultTableModel grid = new DefaultTableModel();
        grid.addColumn("ID Peminjaman");
        grid.addColumn("Judul");
        grid.addColumn("Peminjam");
        grid.addColumn("Tanggal Pinjam");
        grid.addColumn("Status");
        try {
            ResultSet rs = koneksi.getStatement().executeQuery("SELECT * FROM peminjaman");
            while (rs.next()) {
                grid.addRow(new Object[]{
                        rs.getString(1), rs.getString(2), rs.getString(3),
                        rs.getString(4), rs.getString(5)});
            }
            jTable1.setModel(grid);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan mengambil data: \n" + e.getMessage());
        }
    }
    private void kosong() {
        author_txt.setText("");
    }
    public void waktu(){
        Date dt = new Date();
        tgl_chs.setDate(dt);  
    }
    private void isiCmb() {
        try {
            String sqlBuku = "SELECT Judul_Buku FROM buku WHERE Judul_Buku NOT IN (SELECT Judul FROM peminjaman WHERE Status = 'Dipinjam')";
            java.sql.PreparedStatement preparedStatementBuku = koneksi.getPreparedStatement(sqlBuku);
            ResultSet resultSetBuku = preparedStatementBuku.executeQuery();
            while (resultSetBuku.next()) {
                String judulBuku = resultSetBuku.getString("Judul_Buku");
                judul_txt.addItem(judulBuku);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan mengambil data:\n " + e.getMessage());
        }
        try {
            String sqlAnggota = "SELECT Nama FROM anggota WHERE Status <> 'Hitam'";
            java.sql.PreparedStatement preparedStatementAnggota = koneksi.getPreparedStatement(sqlAnggota);
            ResultSet resultSetAnggota = preparedStatementAnggota.executeQuery();

            while (resultSetAnggota.next()) {
                String namaAnggota = resultSetAnggota.getString("Nama");
                peminjam_txt.addItem(namaAnggota);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan mengambil data:\n " + e.getMessage());
        }
    }
    private void cariPeminjaman(String id) {
        DefaultTableModel grid = new DefaultTableModel();
        grid.addColumn("ID Peminjaman");
        grid.addColumn("Judul");
        grid.addColumn("Peminjam");
        grid.addColumn("Tanggal Pinjam");
        grid.addColumn("Status");
        try {
            String query = "SELECT * FROM peminjaman WHERE Peminjam LIKE ?";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(query);
            preparedStatement.setString(1, "%" + id + "%");
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                grid.addRow(new Object[]{
                    rs.getString(1), rs.getString(2), rs.getString(3), 
                    rs.getString(4), rs.getString(5)});
            }jTable1.setModel(grid);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        author_txt = new javax.swing.JTextField();
        tambah_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cari_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cari_btn = new javax.swing.JButton();
        hapus_btn = new javax.swing.JButton();
        perbaruidata_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        dipinjam_chk = new javax.swing.JCheckBox();
        kembali_chk = new javax.swing.JCheckBox();
        edit_btn = new javax.swing.JButton();
        judul_txt = new javax.swing.JComboBox<>();
        peminjam_txt = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tgl_chs = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan Data yang Sesuai !");

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Peminjaman");

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Peminjam ");

        author_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        author_txt.setPreferredSize(new java.awt.Dimension(64, 18));
        author_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                author_txtActionPerformed(evt);
            }
        });

        tambah_btn.setBackground(new java.awt.Color(106, 255, 127));
        tambah_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        tambah_btn.setForeground(new java.awt.Color(0, 0, 126));
        tambah_btn.setText("SIMPAN");
        tambah_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Judul Buku");

        jTable1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID Peminjaman", "Judul", "Peminjam", "Tanggal Pinjam", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cari_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        cari_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_txtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Masukkan Nama Peminjam*");

        cari_btn.setBackground(new java.awt.Color(106, 255, 127));
        cari_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        cari_btn.setForeground(new java.awt.Color(255, 255, 255));
        cari_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\search.png")); // NOI18N
        cari_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_btnActionPerformed(evt);
            }
        });

        hapus_btn.setBackground(new java.awt.Color(106, 255, 127));
        hapus_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        hapus_btn.setForeground(new java.awt.Color(0, 0, 126));
        hapus_btn.setText("HAPUS");
        hapus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_btnActionPerformed(evt);
            }
        });

        perbaruidata_btn.setBackground(new java.awt.Color(106, 255, 127));
        perbaruidata_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        perbaruidata_btn.setForeground(new java.awt.Color(0, 0, 126));
        perbaruidata_btn.setText("PERBARUI DATA");
        perbaruidata_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaruidata_btnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(106, 255, 127));

        jLabel6.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 126));
        jLabel6.setText("DATA PEMINJAMAN");

        back_btn.setBackground(new java.awt.Color(106, 255, 127));
        back_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\arrow (1).png")); // NOI18N
        back_btn.setBorderPainted(false);
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(back_btn)
                .addGap(303, 303, 303)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Status ");

        dipinjam_chk.setBackground(new java.awt.Color(0, 0, 126));
        dipinjam_chk.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        dipinjam_chk.setForeground(new java.awt.Color(255, 255, 255));
        dipinjam_chk.setText("Dipinjam");
        dipinjam_chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dipinjam_chkActionPerformed(evt);
            }
        });

        kembali_chk.setBackground(new java.awt.Color(0, 0, 126));
        kembali_chk.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        kembali_chk.setForeground(new java.awt.Color(255, 255, 255));
        kembali_chk.setText("Dikembalikan");
        kembali_chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_chkActionPerformed(evt);
            }
        });

        edit_btn.setBackground(new java.awt.Color(106, 255, 127));
        edit_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(0, 0, 126));
        edit_btn.setText("EDIT");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        judul_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        judul_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judul_txtActionPerformed(evt);
            }
        });

        peminjam_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        peminjam_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjam_txtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Pinjam");

        tgl_chs.setMinimumSize(new java.awt.Dimension(72, 22));
        tgl_chs.setPreferredSize(new java.awt.Dimension(72, 22));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(author_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peminjam_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_chs, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dipinjam_chk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(kembali_chk))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(tambah_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(perbaruidata_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(hapus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cari_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cari_btn))))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(author_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(cari_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cari_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(perbaruidata_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judul_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peminjam_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tgl_chs, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(dipinjam_chk)
                            .addComponent(kembali_chk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tambah_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ARTPRINT\\panel buku.png")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 49, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cari_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_txtActionPerformed
        String idCari = cari_txt.getText();
        cariPeminjaman(idCari);
    }//GEN-LAST:event_cari_txtActionPerformed

    private void perbaruidata_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbaruidata_btnActionPerformed
        String id_pinjam = author_txt.getText();
        String judul = judul_txt.getSelectedItem().toString();
        String peminjam = peminjam_txt.getSelectedItem().toString();
        String status = dipinjam_chk.isSelected() ? "Dipinjam" : (kembali_chk.isSelected() ? "Dikembalikan" : ""); 
        try {
                String sql = "UPDATE peminjaman SET Judul = ?, Peminjam = ?, Tanggal_Pinjam = ?, Status = ? " +
                             "WHERE ID_Peminjaman = ?";
                java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(sql);
                preparedStatement.setString(1, judul);
                preparedStatement.setString(2, peminjam);
                preparedStatement.setDate(3, new java.sql.Date(tgl_chs.getDate().getTime()));
                preparedStatement.setString(4, status);
                preparedStatement.setString(5, id_pinjam);
                preparedStatement.executeUpdate();
                tampil_peminjaman();
                JOptionPane.showMessageDialog(null, "Data Behasil Diperbarui!");
        } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, "Kesalahan Menyimpan Data!\n" + e.getMessage());
        }
        kosong();
    }//GEN-LAST:event_perbaruidata_btnActionPerformed

    private void hapus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_btnActionPerformed
        int selectedRow = jTable1.getSelectedRow();
         if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang Ingin Dihapus");
            return;
         }
         String id_pinjam = jTable1.getValueAt(selectedRow, 0).toString(); 

         try {
            String sql = "DELETE FROM peminjaman WHERE ID_Peminjaman = ?";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(sql);
            preparedStatement.setString(1, id_pinjam);
            preparedStatement.executeUpdate();
            tampil_peminjaman();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
         } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menghapus Data: " + e.getMessage());
         }
    }//GEN-LAST:event_hapus_btnActionPerformed

    private void tambah_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_btnActionPerformed
        String id_pinjam = author_txt.getText();
        String judul = judul_txt.getSelectedItem().toString();
        String peminjam = peminjam_txt.getSelectedItem().toString();
        String status = dipinjam_chk.isSelected() ? "Dipinjam" : (kembali_chk.isSelected() ? "Dikembalikan" : ""); 
        try {
                String sql = "INSERT INTO peminjaman (ID_Peminjaman, Judul, Peminjam, Tanggal_Pinjam, Status) " +
                             "VALUES (?, ?, ?, ?, ?)";
                java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(sql);
                preparedStatement.setString(1, id_pinjam);
                preparedStatement.setString(2, judul);
                preparedStatement.setString(3, peminjam);
                preparedStatement.setDate(4, new java.sql.Date(tgl_chs.getDate().getTime()));
                preparedStatement.setString(5, status);
                preparedStatement.executeUpdate();
                tampil_peminjaman();
                JOptionPane.showMessageDialog(null, "Data Behasil Disimpan!");
        } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, "Kesalahan Menyimpan Data!\n" + e.getMessage());
        }
        kosong();
    }//GEN-LAST:event_tambah_btnActionPerformed

    private void dipinjam_chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dipinjam_chkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dipinjam_chkActionPerformed

    private void kembali_chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_chkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembali_chkActionPerformed

    private void cari_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_btnActionPerformed
        String idCari = cari_txt.getText();
        cariPeminjaman(idCari);
    }//GEN-LAST:event_cari_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        dispose();
        Home hm = new Home();
        hm.setVisible(true);
        hm.setButtonIcons();
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(Login.EXIT_ON_CLOSE); 
    }//GEN-LAST:event_back_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
           JOptionPane.showMessageDialog(null, "Pilih Baris yang Ingin Diedit");
           return;
        }
        String id_pinjam = jTable1.getValueAt(selectedRow, 0).toString();
        String judul = jTable1.getValueAt(selectedRow, 1).toString();
        String nama = jTable1.getValueAt(selectedRow, 2).toString();
        String tanggal = jTable1.getValueAt(selectedRow, 3).toString();
        String status = jTable1.getValueAt(selectedRow, 4).toString();
        author_txt.setText(id_pinjam);
        judul_txt.setSelectedItem(judul);
        peminjam_txt.setSelectedItem(nama);
    }//GEN-LAST:event_edit_btnActionPerformed

    private void peminjam_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjam_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peminjam_txtActionPerformed

    private void author_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_author_txtActionPerformed

    private void judul_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judul_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judul_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.judul_txtom/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton cari_btn;
    private javax.swing.JTextField cari_txt;
    private javax.swing.JCheckBox dipinjam_chk;
    private javax.swing.JButton edit_btn;
    private javax.swing.JButton hapus_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> judul_txt;
    private javax.swing.JCheckBox kembali_chk;
    private javax.swing.JComboBox<String> peminjam_txt;
    private javax.swing.JButton perbaruidata_btn;
    private javax.swing.JButton tambah_btn;
    private com.toedter.calendar.JDateChooser tgl_chs;
    // End of variables declaration//GEN-END:variables
}
