/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekakhirperpustakaan;

/**
 *
 * @author ASUS
 */
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class PinjamBuku extends javax.swing.JFrame {
private Koneksi koneksi;
    public PinjamBuku() {
        initComponents();
        koneksi = new Koneksi();
        tampil_buku();
    }
    private void tampil_buku() {
        DefaultTableModel grid = new DefaultTableModel();
        grid.addColumn("ID Buku");
        grid.addColumn("Judul Buku");
        grid.addColumn("Pengarang");
        grid.addColumn("Tahun Terbit");
        grid.addColumn("Genre");
        try {
            ResultSet rs = koneksi.getStatement().executeQuery("SELECT * FROM buku");
            while (rs.next()) {
                grid.addRow(new Object[]{
                        rs.getString(1), rs.getString(2), rs.getString(3),
                        rs.getString(4), rs.getString(5)});
            }
            jTable1buku.setModel(grid);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
        }
    }
    private void kosong() {
        judul_txt.setText("");
        pengarang_txt.setText("");
        tahun_txt.setText("");
        id_txt.setText("");
    }
    private void cariBuku(String idCari, String judulCari, String genreCari) {
        DefaultTableModel grid = new DefaultTableModel();
        grid.addColumn("ID Buku");
        grid.addColumn("Judul");
        grid.addColumn("Pengarang");
        grid.addColumn("Tahun Terbit");
        grid.addColumn("Genre");
        try {
            String query = "SELECT * FROM buku WHERE ID_Buku LIKE ? OR Judul_Buku LIKE ? OR Genre LIKE ?";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(query);
            preparedStatement.setString(1, "%" + idCari + "%");
            preparedStatement.setString(2, "%" + judulCari + "%");
            preparedStatement.setString(3, "%" + genreCari + "%");
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                grid.addRow(new Object[]{
                    rs.getString(1), rs.getString(2), rs.getString(3),
                    rs.getString(4), rs.getString(5)});
            } jTable1buku.setModel(grid);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pengarang_txt = new javax.swing.JTextField();
        tambah_btn = new javax.swing.JButton();
        judul_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tahun_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1buku = new javax.swing.JTable();
        cari_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cari_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        genre_cmb = new javax.swing.JComboBox<>();
        hapus_btn = new javax.swing.JButton();
        perbaruiBuku_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 255, 127));
        jLabel1.setText("HALO, SELAMAT DATANG!");

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan Data yang Sesuai !");

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pengarang");

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tahun Terbit");

        pengarang_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        pengarang_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengarang_txtActionPerformed(evt);
            }
        });

        tambah_btn.setBackground(new java.awt.Color(106, 255, 127));
        tambah_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        tambah_btn.setForeground(new java.awt.Color(0, 0, 126));
        tambah_btn.setText("SIMPAN");
        tambah_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_btnActionPerformed(evt);
            }
        });

        judul_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        judul_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judul_txtActionPerformed(evt);
            }
        });
        judul_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                judul_txtKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Judul Buku");

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Buku");

        tahun_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        tahun_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahun_txtActionPerformed(evt);
            }
        });

        id_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });

        jTable1buku.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTable1buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul", "Pengarang", "Tahun Terbit", "Genre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1buku);

        cari_txt.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        cari_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_txtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Masukkan Judul, ID Buku, atau Genre*");

        cari_btn.setBackground(new java.awt.Color(106, 255, 127));
        cari_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        cari_btn.setForeground(new java.awt.Color(0, 0, 126));
        cari_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\search.png")); // NOI18N
        cari_btn.setIconTextGap(8);
        cari_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_btnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Genre");

        genre_cmb.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        genre_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensiklopedia", "Fiksi", "Non-Fiksi", "Novel", "Komik", "Sains" }));

        hapus_btn.setBackground(new java.awt.Color(106, 255, 127));
        hapus_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        hapus_btn.setForeground(new java.awt.Color(0, 0, 126));
        hapus_btn.setText("HAPUS");
        hapus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_btnActionPerformed(evt);
            }
        });

        perbaruiBuku_btn.setBackground(new java.awt.Color(106, 255, 127));
        perbaruiBuku_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        perbaruiBuku_btn.setForeground(new java.awt.Color(0, 0, 126));
        perbaruiBuku_btn.setText("PERBARUI DATA");
        perbaruiBuku_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaruiBuku_btnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(106, 255, 127));

        jLabel10.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 126));
        jLabel10.setText("DAFTAR BUKU");

        back_btn.setBackground(new java.awt.Color(106, 255, 127));
        back_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\arrow (1).png")); // NOI18N
        back_btn.setBorderPainted(false);
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(back_btn)
                .addGap(326, 326, 326)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edit_btn.setBackground(new java.awt.Color(106, 255, 127));
        edit_btn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(0, 0, 126));
        edit_btn.setText("EDIT");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pengarang_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tahun_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(judul_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(genre_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(tambah_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(cari_txt))
                                    .addGap(18, 18, 18)
                                    .addComponent(cari_btn)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(perbaruiBuku_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(hapus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cari_btn)
                                    .addComponent(cari_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(perbaruiBuku_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hapus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(judul_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pengarang_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tahun_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(genre_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addComponent(tambah_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\ARTPRINT\\panel buku.png")); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 57, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pengarang_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengarang_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengarang_txtActionPerformed

    private void tambah_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_btnActionPerformed
        String judul = judul_txt.getText();
        String pengarang = pengarang_txt.getText();
        String tahun = tahun_txt.getText();
        String id = id_txt.getText();
        String genre = genre_cmb.getSelectedItem().toString();
        try {
            String sql = "INSERT INTO buku (ID_Buku, Judul_Buku, Pengarang, Tahun_Terbit, Genre) VALUES (?, ?, ?, ?, ?)";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(sql);
            preparedStatement.setString(1, id);
            preparedStatement.setString(2, judul);
            preparedStatement.setString(3, pengarang);
            preparedStatement.setString(4, tahun);
            preparedStatement.setString(5, genre);
            preparedStatement.executeUpdate();
            tampil_buku();
            JOptionPane.showMessageDialog(null, "Data Behasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Inputan Salah\n" + e.getMessage());
        }
        kosong();
    }//GEN-LAST:event_tambah_btnActionPerformed

    private void tahun_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahun_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahun_txtActionPerformed

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void cari_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_btnActionPerformed
        String idCari = cari_txt.getText();
        String judulCari = cari_txt.getText();
        String genreCari = cari_txt.getText();
        cariBuku(idCari, judulCari, genreCari);
    }//GEN-LAST:event_cari_btnActionPerformed

    private void hapus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_btnActionPerformed
         int selectedRow = jTable1buku.getSelectedRow();
         if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang Ingin Dihapus");
            return;
         }
         String judul = jTable1buku.getValueAt(selectedRow, 0).toString(); 

         try {
            String sql = "DELETE FROM buku WHERE ID_Buku = ?";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(sql);
            preparedStatement.setString(1, judul);
            preparedStatement.executeUpdate();
            tampil_buku();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
         } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menghapus Data: " + e.getMessage());
         }
    }//GEN-LAST:event_hapus_btnActionPerformed

    private void perbaruiBuku_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbaruiBuku_btnActionPerformed
        String id = id_txt.getText();
        String judul = judul_txt.getText();
        String pengarang = pengarang_txt.getText();
        String tahun = tahun_txt.getText();
        String genre = (String) genre_cmb.getSelectedItem();
        try {
            String sql = "UPDATE buku SET Judul_Buku=?, Pengarang=?, Tahun_Terbit=?, Genre=? WHERE ID_Buku=?";
            java.sql.PreparedStatement preparedStatement = koneksi.getPreparedStatement(sql);
            preparedStatement.setString(1, judul);
            preparedStatement.setString(2, pengarang);
            preparedStatement.setString(3, tahun);
            preparedStatement.setString(4, genre);
            preparedStatement.setString(5, id);
            preparedStatement.executeUpdate();
            tampil_buku();
            JOptionPane.showMessageDialog(null, "Data Behasil Diperbarui");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Inputan Salah\n" + e.getMessage());
        }
        kosong();
    }//GEN-LAST:event_perbaruiBuku_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        dispose();
        Home hm = new Home();
        hm.setVisible(true);
        hm.setButtonIcons();
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_back_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        int selectedRow = jTable1buku.getSelectedRow();
        if (selectedRow == -1) {
           JOptionPane.showMessageDialog(null, "Pilih Baris yang Ingin Diedit");
           return;
        }
        String id = jTable1buku.getValueAt(selectedRow, 0).toString();
        String judul = jTable1buku.getValueAt(selectedRow, 1).toString();
        String pengarang = jTable1buku.getValueAt(selectedRow, 2).toString();
        String tahun = jTable1buku.getValueAt(selectedRow, 3).toString();
        String genre = jTable1buku.getValueAt(selectedRow, 4).toString();
        id_txt.setText(id);
        judul_txt.setText(judul);
        pengarang_txt.setText(pengarang);
        tahun_txt.setText(tahun);
    }//GEN-LAST:event_edit_btnActionPerformed

    private void judul_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judul_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judul_txtActionPerformed

    private void judul_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_judul_txtKeyPressed

    }//GEN-LAST:event_judul_txtKeyPressed

    private void cari_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_txtActionPerformed
        String idCari = cari_txt.getText();
        String judulCari = cari_txt.getText();
        String genreCari = cari_txt.getText();
        cariBuku(idCari, judulCari, genreCari);
    }//GEN-LAST:event_cari_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PinjamBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton cari_btn;
    private javax.swing.JTextField cari_txt;
    private javax.swing.JButton edit_btn;
    private javax.swing.JComboBox<String> genre_cmb;
    private javax.swing.JButton hapus_btn;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1buku;
    private javax.swing.JTextField judul_txt;
    private javax.swing.JTextField pengarang_txt;
    private javax.swing.JButton perbaruiBuku_btn;
    private javax.swing.JTextField tahun_txt;
    private javax.swing.JButton tambah_btn;
    // End of variables declaration//GEN-END:variables
}
